version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:5432 # take the 5432 port in the container and expose it as the DB_PORT
    env_file:
      - .env
