# The docker-compose file sets up a multi-container environment. In it, we would run the NestJS app with PostgreSQL and pgAdmin

# specifies the version of the Compose file format we’re using
version: '3.5'

services:
  dev-db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: octavian
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rankman
    networks:
      - rankman
networks:
  rankman:
